# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Setup
title:            King Ghidorah
tagline:          'Follow the light, the light is your guide'
description:      'Space monster blog'
url:              https://gabrielrumiranda.github.io
baseurl:          https://github.com/gabrielrumiranda/gabrielrumiranda.github.io

author:
  name:           'King Ghidorah'
  url:            https://twitter.com/grumiranha

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/gabrielrumiranda/gabrielrumiranda.github.io
